### ISSUE TITLE
error C2040

### ISSUE THREAD

**Issue by hanbingxinjie** [MiroKaku/Veil#10]
编译器环境: vs2022 17.8.4 wdk 10.22621 sdk 10.22621

触发步骤:
1.下载libwsk工程[https://github.com/MiroKaku/libwsk]
2.下载截至今天最新的Veil工程[https://github.com/MiroKaku/Veil]
3.复制Veil工程到libwsk\veil目录
4.vs2022打开libwsk工程,编译.
![image](https://github.com/MiroKaku/Veil/assets/66399650/6e5cd65f-34b4-43b4-a31d-a6ce6c4515ac)

备注:
重复上述操作,下载https://github.com/MiroKaku/Veil/tree/6eed6429c04fd0f24f52800ae0d4d4e62dd41f46替换,编译无错误.

**Comment by MiroKaku** [comment]
重新拉取 libwsk 新版。不过 libwsk.test 的 inf2cat 暂时有点问题。但是不影响
