### ISSUE TITLE
Header file inclusion issue caused by __has_include

### ISSUE THREAD

**Issue by nsky99** [MiroKaku/Veil#11]
#if __has_include(<Windows.h>)
#define  WIN32_LEAN_AND_MEAN
#define  _NTOS_
#define  _DEVIOCTL_
#define  _NTSECAPI_
#include "Veil/Veil.System.WinNT.h"
#include <Windows.h>
#include <Unknwn.h>
#endif

In kernel mode, it will include Windows. h and introduce some structural information of user mode

In some header files, there are also many function declarations in Windows user mode, which may cause link issues if used because this function is not available in kernel mode，RtlFlsAlloc，RtlFlsFree，RtlProcessFlsData..........

**Comment by MiroKaku** [comment]
This is a feature, used by Musa.Core

**Comment by nsky99** [comment]
thanks, Does Musa. core need to include header files for user mode in kernel mode? I just don't think it's reasonable to include user header files in kernel mode.
The library written by the author is indeed very useful👍

**Comment by MiroKaku** [comment]
Musa.Core can use some Ring-3 APIs in the kernel.
